name: Crawl Divi Catalog

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

permissions:
  contents: write


concurrency:
  group: crawl-catalog
  cancel-in-progress: false

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install deps
        run: |
          npm ci
          npx playwright install --with-deps
      - name: Discover packs/pages
        run: npm run discover -- --max 0
      - name: Enrich facets
        run: npm run enrich
      - name: Generate thumbnails
        run: npm run thumbs
      - name: Publish manifest
        run: npm run publish
      - name: Commit and push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist data/work || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore(crawl): update manifest/thumbs [skip ci]"
            git push
          fi

